package com.interviewcracker.entity;
// Generated 14 Jun 2022, 09:42:01 by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * CodeComplexity generated by hbm2java
 */
@Entity
@Table(name = "code_complexity", catalog = "interviewcrackerdb")
@NamedQueries({
	@NamedQuery(name="CodeComplexity.findAll", query= "SELECT c FROM CodeComplexity c ORDER BY c.codeComplexityId"),
	@NamedQuery(name="CodeComplexity.countAll", query= "SELECT count(c) FROM CodeComplexity c"),
	@NamedQuery(name="CodeComplexity.findByName",query="SELECT c FROM CodeComplexity c WHERE c.complexityDesc=:name")
})
public class CodeComplexity implements java.io.Serializable {

	private Integer codeComplexityId;
	private String complexityDesc;

	public CodeComplexity() {
	}

	public CodeComplexity(String complexityDesc) {
		this.complexityDesc = complexityDesc;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "code_complexity_id", unique = true, nullable = false)
	public Integer getCodeComplexityId() {
		return this.codeComplexityId;
	}

	public void setCodeComplexityId(Integer codeComplexityId) {
		this.codeComplexityId = codeComplexityId;
	}

	@Column(name = "complexity_desc", nullable = false, length = 64)
	public String getComplexityDesc() {
		return this.complexityDesc;
	}

	public void setComplexityDesc(String complexityDesc) {
		this.complexityDesc = complexityDesc;
	}

}
