package com.interviewcracker.entity;
// Generated 14 Jun 2022, 09:42:01 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CodeComplexity generated by hbm2java
 */
@Entity
@Table(name = "code_complexity", catalog = "interviewcrackerdb")
public class CodeComplexity implements java.io.Serializable {

	private Integer codeComplexityId;
	private String complexityDesc;
	private Set codingQuestions = new HashSet(0);

	public CodeComplexity() {
	}

	public CodeComplexity(String complexityDesc) {
		this.complexityDesc = complexityDesc;
	}

	public CodeComplexity(String complexityDesc, Set codingQuestions) {
		this.complexityDesc = complexityDesc;
		this.codingQuestions = codingQuestions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "code_complexity_id", unique = true, nullable = false)
	public Integer getCodeComplexityId() {
		return this.codeComplexityId;
	}

	public void setCodeComplexityId(Integer codeComplexityId) {
		this.codeComplexityId = codeComplexityId;
	}

	@Column(name = "complexity_desc", nullable = false, length = 64)
	public String getComplexityDesc() {
		return this.complexityDesc;
	}

	public void setComplexityDesc(String complexityDesc) {
		this.complexityDesc = complexityDesc;
	}

	/*
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "codeComplexity") public Set
	 * getCodingQuestions() { return this.codingQuestions; }
	 * 
	 * public void setCodingQuestions(Set codingQuestions) { this.codingQuestions =
	 * codingQuestions; }
	 */

}
