package com.interviewcracker.entity;
// Generated 14 Jun 2022, 09:42:01 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CodingQuestion generated by hbm2java
 */
@Entity
@Table(name = "coding_question", catalog = "interviewcrackerdb")
public class CodingQuestion implements java.io.Serializable {

	private Integer codingQuestionId;
	private CodeComplexity codeComplexity;
	private String summary;
	private String question;
	private Set codingTestCases = new HashSet(0);
	private Set studentCodings = new HashSet(0);
	private Set studentCodingTests = new HashSet(0);

	public CodingQuestion() {
	}

	public CodingQuestion(CodeComplexity codeComplexity, String summary, String question) {
		this.codeComplexity = codeComplexity;
		this.summary = summary;
		this.question = question;
	}

	public CodingQuestion(CodeComplexity codeComplexity, String summary, String question, Set codingTestCases,
			Set studentCodings, Set studentCodingTests) {
		this.codeComplexity = codeComplexity;
		this.summary = summary;
		this.question = question;
		this.codingTestCases = codingTestCases;
		this.studentCodings = studentCodings;
		this.studentCodingTests = studentCodingTests;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "coding_question_id", unique = true, nullable = false)
	public Integer getCodingQuestionId() {
		return this.codingQuestionId;
	}

	public void setCodingQuestionId(Integer codingQuestionId) {
		this.codingQuestionId = codingQuestionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "code_complexity_id", nullable = false)
	public CodeComplexity getCodeComplexity() {
		return this.codeComplexity;
	}

	public void setCodeComplexity(CodeComplexity codeComplexity) {
		this.codeComplexity = codeComplexity;
	}

	@Column(name = "summary", nullable = false, length = 100)
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "question", nullable = false, length = 1000)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	/*
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "codingQuestion") public Set
	 * getCodingTestCases() { return this.codingTestCases; }
	 * 
	 * public void setCodingTestCases(Set codingTestCases) { this.codingTestCases =
	 * codingTestCases; }
	 * 
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "codingQuestion") public Set
	 * getStudentCodings() { return this.studentCodings; }
	 * 
	 * public void setStudentCodings(Set studentCodings) { this.studentCodings =
	 * studentCodings; }
	 * 
	 * @OneToMany(fetch = FetchType.LAZY, mappedBy = "codingQuestion") public Set
	 * getStudentCodingTests() { return this.studentCodingTests; }
	 * 
	 * public void setStudentCodingTests(Set studentCodingTests) {
	 * this.studentCodingTests = studentCodingTests; }
	 */

}
