package com.interviewcracker.entity;
// Generated 14 Jun 2022, 09:42:01 by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name = "pop_exercise", catalog = "interviewcrackerdb")
@NamedQueries({
	@NamedQuery(name="POPExercises.findAll", query= "SELECT c FROM POPExercises c ORDER BY c.popExerciseId"),
	@NamedQuery(name="POPExercises.findPOPExercise", query= "SELECT c FROM POPExercises c where c.week=:week AND c.lesson=:lesson"),
	@NamedQuery(name="POPExercises.findByExerciseId", query= "SELECT c FROM POPExercises c where c.popExerciseId=:exerciseId")
})
public class POPExercises implements java.io.Serializable {

	private Integer popExerciseId;
	private String week;
	private String lesson;
	private String language;
	private String question;
	private String output;
	private String code;
	private String anscode;
	private Character status;

	public POPExercises() {
	}

	public POPExercises(String week, String lesson,String language, String question, String output, 
			String code, String anscode,Character status) {
		this.week = week;
		this.lesson = lesson;
		this.language = language;
		this.question = question;
		this.output = output;
		this.code = code;
		this.anscode = anscode;
		this.status=status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pop_exercise_id", unique = true, nullable = false)
	public Integer getPopExerciseId() {
		return this.popExerciseId;
	}

	public void setPopExerciseId(Integer popExerciseId) {
		this.popExerciseId = popExerciseId;
	}
	
	@Column(name = "week", unique = true, nullable = false)
	public String getWeek() {
		return this.week;
	}

	public void setWeek(String week) {
		this.week = week;
	}

	@Column(name = "lesson", unique = true, nullable = false, length = 64)
	public String getLesson() {
		return this.lesson;
	}

	public void setLesson(String lesson) {
		this.lesson = lesson;
	}

	@Column(name = "language")
	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}
	
	@Column(name = "question")
	public String getQuestion() {
		return question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "output")
	public String getOutput() {
		return output;
	}

	public void setOutput(String output) {
		this.output = output;
	}

	@Column(name = "code")
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "anscode")
	public String getAnscode() {
		return anscode;
	}

	public void setAnscode(String anscode) {
		this.anscode = anscode;
	}

	@Column(name = "status", length = 1)
	public Character getStatus() {
		return status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}
	
}