package com.interviewcracker.entity;
// Generated 14 Jun 2022, 09:42:01 by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name = "pop_exercise", catalog = "interviewcrackerdb")
@NamedQueries({
	@NamedQuery(name="POPExercises.findAll", query= "SELECT c FROM POPExercises c ORDER BY c.popExerciseId")
})
public class POPExercises implements java.io.Serializable {

	private Integer popExerciseId;
	private String week;
	private String lesson;

	public POPExercises() {
	}

	public POPExercises(String week, String lesson) {
		this.week = week;
		this.lesson = lesson;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pop_exercise_id", unique = true, nullable = false)
	public Integer getPopExerciseId() {
		return this.popExerciseId;
	}

	public void setPopExerciseId(Integer popExerciseId) {
		this.popExerciseId = popExerciseId;
	}
	
	@Column(name = "week", unique = true, nullable = false)
	public String getWeek() {
		return this.week;
	}

	public void setWeek(String week) {
		this.week = week;
	}

	@Column(name = "lesson", unique = true, nullable = false, length = 64)
	public String getLesson() {
		return this.lesson;
	}

	public void setLesson(String lesson) {
		this.lesson = lesson;
	}
}