package com.interviewcracker.entity;
// Generated 14 Jun 2022, 09:42:01 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Staffs generated by hbm2java
 */
@Entity
@Table(name = "staffs", catalog = "interviewcrackerdb", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
@NamedQueries({
	@NamedQuery(name="Staffs.findAll", query= "SELECT u FROM Staffs u ORDER BY u.fullname"),
	@NamedQuery(name="Staffs.countAll", query= "SELECT count(u) FROM Staffs u"),
	@NamedQuery(name="Staffs.findByEmail",query="SELECT u FROM Staffs u WHERE u.email=:email"),
	@NamedQuery(name="Staffs.checkLogin",query="SELECT u from Staffs u WHERE u.email=:email and u.password=:password")
})
public class Staffs implements java.io.Serializable {

	private Integer staffId;
	private String email;
	private String fullname;
	private String password;
	private byte[] profilepic;

	public Staffs() {
	}

	public Staffs(String email, String fullname, String password) {
		this.email = email;
		this.fullname = fullname;
		this.password = password;
	}

	public Staffs(String email, String fullname, String password, byte[] profilepic) {
		this.email = email;
		this.fullname = fullname;
		this.password = password;
		this.profilepic = profilepic;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "staff_id", unique = true, nullable = false)
	public Integer getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Integer staffId) {
		this.staffId = staffId;
	}

	@Column(name = "email", unique = true, nullable = false, length = 64)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "fullname", nullable = false, length = 30)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "profilepic")
	public byte[] getProfilepic() {
		return this.profilepic;
	}

	public void setProfilepic(byte[] profilepic) {
		this.profilepic = profilepic;
	}

}
