package com.interviewcracker.entity;
// Generated 14 Jun 2022, 09:42:01 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentCoding generated by hbm2java
 */
@Entity
@Table(name = "student_coding", catalog = "interviewcrackerdb")
public class StudentCoding implements java.io.Serializable {

	private Integer studentCodingId;
	private CodingQuestion codingQuestion;
	private Students students;
	private Integer completionPercent;
	private Integer hitCount;

	public StudentCoding() {
	}

	public StudentCoding(CodingQuestion codingQuestion, Students students) {
		this.codingQuestion = codingQuestion;
		this.students = students;
	}

	public StudentCoding(CodingQuestion codingQuestion, Students students, Integer completionPercent,
			Integer hitCount) {
		this.codingQuestion = codingQuestion;
		this.students = students;
		this.completionPercent = completionPercent;
		this.hitCount = hitCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "student_coding_id", unique = true, nullable = false)
	public Integer getStudentCodingId() {
		return this.studentCodingId;
	}

	public void setStudentCodingId(Integer studentCodingId) {
		this.studentCodingId = studentCodingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coding_question_id", nullable = false)
	public CodingQuestion getCodingQuestion() {
		return this.codingQuestion;
	}

	public void setCodingQuestion(CodingQuestion codingQuestion) {
		this.codingQuestion = codingQuestion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "students_id", nullable = false)
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Column(name = "completion_percent")
	public Integer getCompletionPercent() {
		return this.completionPercent;
	}

	public void setCompletionPercent(Integer completionPercent) {
		this.completionPercent = completionPercent;
	}

	@Column(name = "hit_count")
	public Integer getHitCount() {
		return this.hitCount;
	}

	public void setHitCount(Integer hitCount) {
		this.hitCount = hitCount;
	}

}
