package com.interviewcracker.entity;
// Generated 14 Jun 2022, 09:42:01 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StudentCourse generated by hbm2java
 */
@Entity
@Table(name = "student_course", catalog = "interviewcrackerdb")
public class StudentCourse implements java.io.Serializable {

	private Integer studentCourseId;
	private Courses courses;
	private Students students;
	private Integer completionPercent;
	private Integer hitCount;

	public StudentCourse() {
	}

	public StudentCourse(Courses courses, Students students) {
		this.courses = courses;
		this.students = students;
	}

	public StudentCourse(Courses courses, Students students, Integer completionPercent, Integer hitCount) {
		this.courses = courses;
		this.students = students;
		this.completionPercent = completionPercent;
		this.hitCount = hitCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "student_course_id", unique = true, nullable = false)
	public Integer getStudentCourseId() {
		return this.studentCourseId;
	}

	public void setStudentCourseId(Integer studentCourseId) {
		this.studentCourseId = studentCourseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courses_id", nullable = false)
	public Courses getCourses() {
		return this.courses;
	}

	public void setCourses(Courses courses) {
		this.courses = courses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "students_id", nullable = false)
	public Students getStudents() {
		return this.students;
	}

	public void setStudents(Students students) {
		this.students = students;
	}

	@Column(name = "completion_percent")
	public Integer getCompletionPercent() {
		return this.completionPercent;
	}

	public void setCompletionPercent(Integer completionPercent) {
		this.completionPercent = completionPercent;
	}

	@Column(name = "hit_count")
	public Integer getHitCount() {
		return this.hitCount;
	}

	public void setHitCount(Integer hitCount) {
		this.hitCount = hitCount;
	}

}
